name: language_code
description: Get the current language code and Locale of the device. Also includes almost the language codes with English names and native names.
version: 0.6.0-rc.3
homepage: https://github.com/lamnhan066/language_code

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: ^8.1.1
  http: ^1.5.0
  html: ^0.15.6
  dart_style: ^3.1.2
